"""Add Created By to Room

Revision ID: c2ec4f94e222
Revises: 8184c597fbdc
Create Date: 2023-12-13 21:12:30.781930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ec4f94e222'
down_revision = '8184c597fbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_room_created_by', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
