"""Your migration message

Revision ID: f68c95abcca9
Revises: 4b5a625b0f1b
Create Date: 2023-12-21 22:27:49.792168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68c95abcca9'
down_revision = '4b5a625b0f1b'
branch_labels = None
depends_on = None


def upgrade():
    # Add the new columns
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=255), nullable=True))

    # Set default values and constraints
    op.execute("UPDATE users SET email='default@example.com' WHERE email IS NULL")
    op.alter_column('users', 'email', nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['verification_token'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
